### ISSUE TITLE
Errore Temp

### ISSUE THREAD

**Issue by NezukoKamando** [MrCreeper2010/SMTool#2]
Quando avvio il tool mi dice
[-] Prefetch or %temp% unreacheable, possible cacls method?

Eccezione non gestita: System.TypeInitializationException: L'inizializzatore di tipo di 'SMT.helpers.SMTHelper' ha generato un'eccezione. ---> System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\Korei\AppData\Local\Temp'.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileSystemEnumerableIterator`1.CommonInit()
   in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   in System.IO.Directory.GetFiles(String path)
   in SMT.helpers.SMTHelper..cctor()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in SMT.helpers.SMTHelper.Wait()
   in SMT.SMT.Main()
   
   ma il mio user e "polic"

**Comment by MrCreeper2010** [comment]
A quanto pare vi è un chiaro problema nell'individuare l'utente del pc. Tale bug già mi è stato reportato tanto tempo fa ma la percentuale di utenti che avevano riscontrato tale bug era molto bassa rispetto agl'altri bugs. 
Tecnicamente parlando non dipende direttamente da me e il modo in cui ottengo l'utente del pc è corretto ma a quanto pare c'è qualcosa che non va. Aggiungerò alla prossima release, nel caso qualcuno dovesse riscontrare tale bug, una richiesta in cui l'utente è pregato di inserire l'utente del PC ovviando al problema o mi metterò alla ricerca di uno strumento per alzare al massimo i permessi del mio programma. 
La prossima release è prevista non appena finirò di implementare quanti più metodi possibili richiesti dagli utenti, già sono a buon punto. Ad ogni modo, ti ringrazio di cuore per esserti interessato sia al tool che allo sviluppo di quest'ultimo segnalando un bug molto grave.

**Comment by NezukoKamando** [comment]
Grazie mille lo stavo provando un'attimo da me

**Comment by MrCreeper2010** [comment]
Affinchè possa investigare con maggiore efficacia sul bug potresti scrivere su telegram a questo bot: @CheatReleaseSupport_bot chiedendo di me e dicendo che sei il tipo di github? Mi aiuterebbe molto parlare e cercare una soluzione su AnyDesk
