### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by DarkManers** [MrCreeper2010/SMTool#3]
Non ho capito come scaricare il tool please help! tnx ;)

**Comment by MrCreeper2010** [comment]
Alla destra del codice vi è una sezione chiamata "Releases". Cliccando su questa sezione apparirà un changelog enorme e al di sotto di questo testo vi sarà SMT.exe e poi il source code nei vari formati che propone github. Ti basterà semplicemente cliccare su SMT.exe scaricando così l'eseguibile. Ricorda, **mai compilare ed eseguire in controllo delle versioni che sono state committate e non rilasciate. Se non sono state rilasciate pubblicamente ci sarà un motivo no?**
