### ISSUE TITLE
Problema all'avvio

### ISSUE THREAD

**Issue by NonUsoQuestoSito** [MrCreeper2010/SMTool#4]
(Problema risolto)

**Comment by MrCreeper2010** [comment]
"Quando cerco di avviare il tool mi viene detto "Impossibile eseguire questa app sul tuo PC, per cercare una versione per il tuo pc contatta il distributore del sofware". Mi viene dato l'errore sia quando lo eseguo normalmente sia quando lo eseguo da amministratore. Windows è all'ultima versione."

Non è un errore di SMT ma piuttosto credo sia dovuto ai conflitti con l'antivirus. Chiudo.
